#name, main, version and api are required
name: ExamplePlugin
main: ExamplePlugin\MainClass
version: 1.1.0
api: 3.0.0

load: POSTWORLD
author: hotiovip
description: Example plugin showing the new API
website: https://github.com/pmmp/ExamplePlugin
commands:
 saluta:
  description: Saluta
  usage: "/saluta"
  permission: exampleplugin.command.saluta
permissions:
 exampleplugin.command.example:
  description: "Permette di usare questo comando"
  default: true
